workflows:
  android-build:
    name: Flex Yemen Auto Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    scripts:
      - name: Generate Android Platform Files
        script: | 
          # هذا السطر يحل محل عدم وجود فلوتر عندك
          flutter create --platforms android .
      - name: Get dependencies
        script: | 
          flutter pub get
      - name: Build Android Release
        script: | 
          flutter build apk --release --build-name=1.0.0 --build-number=1
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - YOUR_EMAIL@gmail.com # ضع إيميلك هنا لتصلك الرسالة عند النجاح
