workflows:
  android-release:
    name: Flex Yemen Android Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      groups:
        - google_play_credentials
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter packages pub get
      - name: Build Android Release
        script: |
          flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - YOUR_EMAIL@gmail.com # ضع إيميلك هنا لتصلك النسخة فور جهوزيتها
